import { webkit } from "playwright";
const BASE="https://celengin-mei-baskara.netlify.app";
const b=await webkit.launch({headless:true});
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});
const p=await ctx.newPage();
await p.goto(`${BASE}/login`,{waitUntil:"networkidle"});
await p.fill('input[type="email"]',process.env.SHOT_EMAIL);
await p.fill('input[type="password"]',process.env.SHOT_PW);
await p.click('button[type="submit"]');
await p.waitForURL(u=>!u.pathname.includes("/login"),{timeout:20000}).catch(()=>{});
await p.waitForTimeout(3000);
await p.screenshot({path:"/tmp/celengin-shots/webkit-viewport.png"});
const geo = await p.evaluate(() => {
  const labels=[...document.querySelectorAll('div')].filter(d=>d.textContent==='Pengeluaran bulan ini');
  if(!labels.length) return 'hero label not found';
  const card=labels[0].closest('div[style*="linear-gradient"]')||labels[0].parentElement;
  const r=card.getBoundingClientRect();
  return {h:Math.round(r.height), w:Math.round(r.width), parentDisplay:getComputedStyle(card.parentElement).display};
});
console.log("WEBKIT HERO GEO:", JSON.stringify(geo));
await b.close();
